### ISSUE TITLE
Use environment variable in the configuration

### ISSUE THREAD

**Issue by OnoArnaldo** [OnoArnaldo/py_staticpage_builder#9]
Suggested syntax:

`{key-name}: "$ENV:{VAR_NAME}"`

Example:

```yaml
config:
  # ...
  builder:
    # ...
    cdn:
      execute: false
      service_name: "$ENV:STATIC_CDN_SERV_NAME"
      region_name: "$ENV:STATIC_CDN_REG_NAME"
      # ...
```
